<?php

declare(strict_types=1);

namespace Ergonode\ProductConsumer\Test\Integration\Model\Magento;

use Ergonode\ProductConsumer\Model\Magento\ProductUrlKeyWriter;
use Magento\Catalog\Api\ProductRepositoryInterface;
use Magento\Catalog\Model\Product;
use Magento\Catalog\Test\Fixture\Product as ProductFixture;
use Magento\CatalogUrlRewrite\Model\ProductUrlRewriteGenerator;
use Magento\Framework\App\ResourceConnection;
use Magento\Framework\DataObject;
use Magento\TestFramework\Fixture\AppIsolation;
use Magento\TestFramework\Fixture\DataFixture;
use Magento\TestFramework\Fixture\DataFixtureStorage;
use Magento\TestFramework\Fixture\DataFixtureStorageManager;
use Magento\TestFramework\Fixture\DbIsolation;
use Magento\TestFramework\Helper\Bootstrap;
use PHPUnit\Framework\TestCase;

#[
    AppIsolation(true),
    DbIsolation(false)
]
class ProductUrlKeyWriterIntegrationTest extends TestCase
{
    private ProductUrlKeyWriter $urlKeyWriter;
    private ProductRepositoryInterface $productRepository;
    private ResourceConnection $resourceConnection;
    private DataFixtureStorage $fixtures;

    protected function setUp(): void
    {
        $objectManager = Bootstrap::getObjectManager();
        $this->urlKeyWriter = $objectManager->get(ProductUrlKeyWriter::class);
        $this->productRepository = $objectManager->get(ProductRepositoryInterface::class);
        $this->resourceConnection = $objectManager->get(ResourceConnection::class);
        $this->fixtures = DataFixtureStorageManager::getStorage();
    }

    #[
        DataFixture(
            ProductFixture::class,
            [
                'sku' => 'ergonode-url-key-writer-%uniqid%',
                'name' => 'Ergonode URL Key Writer %uniqid%',
                'price' => 10,
                'visibility' => 4,
            ],
            as: 'product'
        )
    ]
    public function testMappedUrlKeyUsesMagentoNormalizationAndRegeneratesUrlRewrite(): void
    {
        /** @var DataObject $fixture */
        $fixture = $this->fixtures->get('product');
        $productId = (int)$fixture->getId();
        $sku = (string)$fixture->getSku();

        $this->urlKeyWriter->write($productId, [0 => '  Mapped / URL Key  '], []);

        $product = $this->productRepository->get($sku, false, null, true);
        self::assertInstanceOf(Product::class, $product);
        self::assertSame('mapped-url-key', $product->getData('url_key'));
        self::assertNotEmpty($this->getMappedUrlRewrites($productId));
    }

    /**
     * @return array<int, array<string, mixed>>
     */
    private function getMappedUrlRewrites(int $productId): array
    {
        $connection = $this->resourceConnection->getConnection();

        return $connection->fetchAll(
            $connection->select()
                ->from($this->resourceConnection->getTableName('url_rewrite'), ['request_path', 'store_id'])
                ->where('entity_type = ?', ProductUrlRewriteGenerator::ENTITY_TYPE)
                ->where('entity_id = ?', $productId)
                ->where('request_path LIKE ?', 'mapped-url-key%')
                ->where('redirect_type = ?', 0)
                ->where('is_autogenerated = ?', 1)
        );
    }
}
